// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssjfpjcgqfzsgiovxtfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzamZwamNncWZ6c2dpb3Z4dGZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzODcxNDMsImV4cCI6MjA2Mzk2MzE0M30.5AzWBtVGjz8KbLyYO_WyyjH4tzv3UJX12LEwW-Solug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});